version: "3"
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx/log
    # restart: always
  app1:
    image: httpd:2.4-alpine
    volumes:
      - ./app1:/usr/local/apache2/htdocs
    # restart: always
  app2:
    image: httpd:2.4-alpine
    volumes:
      - ./app2:/usr/local/apache2/htdocs
    # restart: always
